### ISSUE TITLE
AttributeError: 'Program' object has no attribute '_program'

### ISSUE THREAD

**Issue by matthewarthur** [NVIDIA/FastPhotoStyle#10]
Running on ubuntu 16.04 with setup as outlined, and receive this error: 
Elapsed time in stylization: 3.351004
Elapsed time in propagation: 15.440228
Traceback (most recent call last):
  File "demo.py", line 75, in <module>
    out_img = smooth_filter(output_image_path, content_image_path, f_radius=15, f_edge=1e-1)
  File "/home/ubuntu/FastPhotoStyle-master/smooth_filter.py", line 392, in smooth_filter
    best_ = smooth_local_affine(output_, input_, 1e-7, 3, H, W, f_radius, f_edge)
  File "/home/ubuntu/FastPhotoStyle-master/smooth_filter.py", line 333, in smooth_local_affine
    program = Program(src, 'best_local_affine_kernel.cu')
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pynvrtc/compiler.py", line 52, in __init__
    include_names)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pynvrtc/interface.py", line 185, in nvrtcCreateProgram
    c_char_p(src), c_char_p(name),
TypeError: bytes or integer address expected instead of str instance
Exception ignored in: <bound method Program.__del__ of <pynvrtc.compiler.Program object at 0x7f3e7eed4f28>>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pynvrtc/compiler.py", line 56, in __del__
    self._interface.nvrtcDestroyProgram(self._program)
AttributeError: 'Program' object has no attribute '_program'

**Comment by mingyuliutw** [comment]
As stated in the USAGE.md, the demo code runs on Python2.

**Comment by mingyuliutw** [comment]
@matthewarthur Could you comment if switching to Python2 resolves the issue? Based on the error message, the problem is from the post processing step, which utilize cupy and pynvrtc libraries. I only know how to make them work in Python2.

**Comment by SelvamArul** [comment]
@mingyuliutw I had this same error and I was running with python3.5 too. Running with python2.7 works. Thanks for open-sourcing this very impressive work.

**Comment by SelvamArul** [comment]
@mingyuliutw The changes needed for python3 compatibility is trivial. I did the changes and tested with py3.5. If you are interested, I can send a PR.

**Comment by mingyuliutw** [comment]
@SelvamArul That will be great. Please send a PR.

**Comment by Piroman3D** [comment]
@SelvamArul , Could you also share that fix for compatibility?

**Comment by SelvamArul** [comment]
@Piroman3D #39 is the PR I did for the compatibility. Hope this helps.

**Comment by sgflower66** [comment]
Now, I use it in pyhon3.6, pytorch0.4.0. I find that if  pynvrtc==8.0 ,  the same problem happened. However, it can work when I use pynvrtc==9.2.
