### ISSUE TITLE
RuntimeError: MAGMA gesdd : the updating process of SBDSDC did not converge

### ISSUE THREAD

**Issue by t0mst0ne** [NVIDIA/FastPhotoStyle#13]
Enviroment: build from docker 

sudo docker run --runtime=nvidia -v /GITHUB/FastPhotoStyle:/home -i -t fastphotostyle:v1.0 /bin/bash

The pytorch found the GPU
torch.cuda.get_device_name(0)  => 'GeForce .....'

python demo.py  => I Got the error below, does that mean the code didn't use cuda mostly ?

#######################################################
Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
Traceback (most recent call last):
  File "demo.py", line 68, in <module>
    stylized_img = p_wct.transform(cont_img, styl_img, cont_seg, styl_seg)
  File "/home/photo_wct.py", line 47, in transform
    csF3 = self.__feature_wct(cF3, sF3, cont_seg, styl_seg)
  File "/home/photo_wct.py", line 119, in __feature_wct
    tmp_target_feature = self.__wct_core(cont_feat_view, styl_feat_view)
  File "/home/photo_wct.py", line 154, in __wct_core
    c_u, c_e, c_v = torch.svd(contentConv, some=False)
RuntimeError: MAGMA gesdd : the updating process of SBDSDC did not converge (error: 14) at /opt/conda/conda-bld/pytorch_1518238581238/work/torch/lib/THC/generic/THCTensorMathMagma.cu:325

**Comment by t0mst0ne** [comment]
solved -> Possible environment problem

change the environment to cuda9.0 and correspond cudnn , nvidia-smi 390.30
Ubutun 17.10 , using Docker 
Hardware :  1080 Ti

Its OK now without error , thanks
