### ISSUE TITLE
 CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed

### ISSUE THREAD

**Issue by yogeshbalaji** [NVIDIA/FastPhotoStyle#20]
I am running with cuda9.1 and using similar setup as mentioned in the user manual. Getting the following error:

Elapsed time in stylization: 2.802349
Elapsed time in propagation: 18.942090
Elapsed time in post processing: 0.243305
Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    output_image_path=args.output_image_path,
  File "/scratch0/Projects/style_transfer/FastPhotoStyle/process_stylization.py", line 63, in stylization
    out_img = smooth_filter(output_image_path, content_image_path, f_radius=15, f_edge=1e-1)
  File "/scratch0/Projects/style_transfer/FastPhotoStyle/smooth_filter.py", line 391, in smooth_filter
    best_ = smooth_local_affine(output_, input_, 1e-7, 3, H, W, f_radius, f_edge)
  File "/scratch0/Projects/style_transfer/FastPhotoStyle/smooth_filter.py", line 335, in smooth_local_affine
    m.load(bytes(ptx.encode()))
  File "cupy/cuda/function.pyx", line 175, in cupy.cuda.function.Module.load
  File "cupy/cuda/function.pyx", line 176, in cupy.cuda.function.Module.load
  File "cupy/cuda/driver.pyx", line 141, in cupy.cuda.driver.moduleLoadData
  File "cupy/cuda/driver.pyx", line 72, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed

**Comment by exist2disappear** [comment]
I have same problem on cuda 9.1 and I think it  because my Display Driver is too old?(384.111)

**Comment by daniel-saunders** [comment]
Same here - i'm (trying) to use a gt 1030 graphics card, and i wonder if its the card that's the problem.

**Comment by SeaOfOcean** [comment]
same problem on cuda 9.0

**Comment by okdshin** [comment]
It seems we have to install `cupy-cudaXX` (e.g. `cupy-cuda91`) rather than `cupy`. https://docs-cupy.chainer.org/en/stable/install.html#install-cupy

**Comment by okdshin** [comment]
It seems we have to install `cupy-cudaXX` (e.g. `cupy-91`) rather than `cupy`. https://docs-cupy.chainer.org/en/stable/install.html#install-cupy
