### ISSUE TITLE
How to run on Google Colab Jupyter Notbook?

### ISSUE THREAD

**Issue by rraallvv** [NVIDIA/FastPhotoStyle#22]
This is how I've tried to run the demo on a Jupyter Notebook on Google Colab

## Download the models 
```
# Download the file we just uploaded.
#
# Replace the assignment below with your file ID
# to download a different file.
#
# A file ID looks like: 1uBtlaggVyWshwcyP6kEI-y_W3P8D26sz
file_id = '1ENgQm9TgabE1R99zhNf5q6meBvX6WFuq'

import io
import sys
from googleapiclient.http import MediaIoBaseDownload
from googleapiclient.discovery import build
drive_service = build('drive', 'v3')

filename = 'data.zip'

request = drive_service.files().get_media(fileId=file_id)
downloaded = io.FileIO(filename, 'wb')
downloader = MediaIoBaseDownload(downloaded, request)
done = False
while done is False:
  status, done = downloader.next_chunk()
  sys.stdout.write("\r{0:.0f}%".format(status.progress() * 100))
  sys.stdout.flush()

print('\rDownloaded file: {}'.format(filename))
```

## Install dependencies
```
# Anaconda
! wget https://repo.continuum.io/archive/Anaconda2-5.1.0-Linux-x86_64.sh
! bash Anaconda2-5.1.0-Linux-x86_64.sh -b -p $HOME/anaconda

# PyTorch
! PATH=$HOME/anaconda/bin:$PATH && conda install pytorch=0.3.0 torchvision cuda90 -y -c pytorch
  
# Image magic
! apt-get install -y axel imagemagick

# Cupy
! PATH=$HOME/anaconda/bin:$PATH && pip install scikit-umfpack
! PATH=$HOME/anaconda/bin:$PATH && pip install -U setuptools
! PATH=$HOME/anaconda/bin:$PATH && pip install pynvrtc

! apt -y install libcusparse8.0 libnvrtc8.0 libnvtoolsext1
! ln -snf /usr/lib/x86_64-linux-gnu/libnvrtc-builtins.so.8.0 /usr/lib/x86_64-linux-gnu/libnvrtc-builtins.so
! PATH=$HOME/anaconda/bin:$PATH && pip install 'cupy-cuda90==4.0.0b4' 'chainer==4.0.0b4'
```

## Copy the repository and the models
```
! git clone https://github.com/NVIDIA/FastPhotoStyle
! unzip data.zip -d FastPhotoStyle
! mkdir -p FastPhotoStyle/images && rm -fr FastPhotoStyle/images/* && mkdir -p FastPhotoStyle/results && rm -fr FastPhotoStyle/results/*
! axel -n 1 http://freebigpictures.com/wp-content/uploads/shady-forest.jpg --output=FastPhotoStyle/images/content1.png  
! axel -n 1 https://vignette.wikia.nocookie.net/strangerthings8338/images/e/e0/Wiki-background.jpeg/revision/latest?cb=20170522192233 --output=FastPhotoStyle/images/style1.png
! cd FastPhotoStyle/images && convert -resize 25% content1.png content1.png && convert -resize 50% style1.png style1.png
```

## Run demo
`! cd FastPhotoStyle && python demo.py
`

## Output
```
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import process_stylization
  File "/content/FastPhotoStyle/process_stylization.py", line 17, in <module>
    from smooth_filter import smooth_filter
  File "/content/FastPhotoStyle/smooth_filter.py", line 326, in <module>
    from cupy.cuda import function
ImportError: No module named cupy.cuda
```

I'm not sure what dependencies are missing or whether Cuda is already installed in the VM.

**Comment by wesleyw72** [comment]
After a bit of hacking away, I have managed to get it to work.

It does not seem like CUDA is installed in a usable way on the Google Colab instances.
My solution was to install CUDA, cuDNN and NCCL and then try. 

You can see the steps I have done [here](https://drive.google.com/file/d/14OyDrmxzBmkJ8H51iodPE2aXHzCduKJP/view?usp=sharing). Note that this is very much a work in progress, there are still artefacts of previous runs. When I get a bit more time I will try and get a fresh instance and rerun from start to finish, but for the moment do not take the output of some of the commands to be what you should expect.

There are some downloads you will need to do in order to get it working, but they are written in the doc. Let me know how you get on or if you run into any problems.

**Comment by rraallvv** [comment]
@wesleyw72 , thanks for looking into it, you have put a considerable amount of work to get it to run. It's highly appreciated.

If anyone needs some more clarification, feel free to re-open the issue.

**Comment by ShawnOakley** [comment]
I'm having issues with this step:
https://colab.research.google.com/drive/1VQbYFDUAAFnudbugTzqV6rWg7WAEp_Eq#scrollTo=TUkwkgIas_yF

How do I get the deb file from local filesystem into the colab notebook?

**Comment by nuthinking** [comment]
@wesleyw72 I believe that trying your notebook messed up with my current working directory. Now all my other notebooks can't access the `drive` folder anymore. Any ideas how to fix this? Thanks!

**Comment by jcsh4326** [comment]
install cuda fail.
I just run the demo in playground model and got this error
```
dpkg: error processing archive /tmp/apt-dpkg-install-caKkPC/186-nvidia-396_396.44-0ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/egl/egl_external_platform.d/10_nvidia_wayland.json', which is also in package libnvidia-gl-396:amd64 396.54-0ubuntu0~gpu18.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```
I tried to install cuda in a new colab environment and got the same error.

**Comment by leolle** [comment]
@wesleyw72 Hi, I install all the dependencies like you said, but the colab runs out of memory when running demo.py.

**Comment by FantasyJXF** [comment]
I just use the colab to run the model, only one probelm
```
demo_example1.sh: convert: not found
```

what's the `convert` command?

**Comment by FantasyJXF** [comment]
sudo apt-get install imagemagick

**Comment by galoisgroupcn** [comment]
@FantasyJXF @leolle @jcsh4326 

我在 Colab 上取得了一些进展。为方便交流，打算建个QQ群。各位感兴趣加入吗？

如有，请留言 QQ 号。我来加你们。谢谢！

季雪都
Amber Ji

QQ：1543386340

**Comment by galoisgroupcn** [comment]
> @wesleyw72 , thanks for looking into it, you have put a considerable amount of work to get it to run. It's highly appreciated.
> 
> If anyone needs some more clarification, feel free to re-open the issue.

@wesleyw72 Hi Wesley! Thanks for the time & effort you put in.

Google Colab provides built-in CuPy by default, so you may not need to install it manually.

Also since Colab has a built-in CUDA 10.0. I don't think it a good idea to uninstall CUDA 10.0 and reinstall CUDA 8.0.

It seems your program is based on Python 2.7. Would you like to try on Python 3.6?

@rraallvv Hi rraallvv, would you like to reopen this issue please?

**Comment by galoisgroupcn** [comment]
@leolle @rraallvv @wesleyw72 @jcsh4326 @FantasyJXF 
Hi All!

I use the built-in CuPy by default, and encounter the following error:

ModuleNotFoundError: No module named 'cupy'

This is my Notebook:

https://colab.research.google.com/drive/1oBgdJgXCLlUQhpwPoG1Uom3OKTzHR4BF

Hope you could offer some help. Thank you :)

Amber Ji

**Comment by sayakpaul** [comment]
Here's.a bit simpler Colab Notebook built on top of what @wesleyw72 did: https://colab.research.google.com/gist/sayakpaul/3409a7377e74b596e22818b4a9713795/scratchpad.ipynb. Just change the runtime to GPU and you should be good to go.
