### ISSUE TITLE
ValueError: cannot reshape array of size 67500 into shape (22500,)

### ISSUE THREAD

**Issue by fangzhuangzz** [NVIDIA/FastPhotoStyle#37]
Traceback (most recent call last):
  File "demo.py", line 43, in <module>
    cuda=args.cuda,
  File "/home/zhuangwei.zw/FastPhotoStyle/process_stylization.py", line 62, in stylization
    stylized_img = p_wct.transform(cont_img, styl_img, cont_seg, styl_seg)
  File "/home/zhuangwei.zw/FastPhotoStyle/photo_wct.py", line 35, in transform
    csF4 = self.__feature_wct(cF4, sF4, cont_seg, styl_seg)
  File "/home/zhuangwei.zw/FastPhotoStyle/photo_wct.py", line 88, in __feature_wct
    cont_mask = np.where(t_cont_seg.reshape(t_cont_seg.shape[0] * t_cont_seg.shape[1]) == l)
ValueError: cannot reshape array of size 67500 into shape (22500,)

I followed the Example2 manual, but throw this error.

**Comment by fangzhuangzz** [comment]
command:
python demo.py --content_image_path content_json/img.png  --content_seg_path content_json/label.png --style_image_path 
style_json/img.png --style_seg_path style_json/label.png  --output_image_path  results/0317.dt.png
