### ISSUE TITLE
THCudaCheck FAIL / RuntimeError: cuda runtime error (30) : unknown error

### ISSUE THREAD

**Issue by ilyaskuzu** [NVIDIA/FastPhotoStyle#45]
i have used the exact same setup as the code usage suggested. (i even make a clean install for ubuntu) i am using geforce GTX 950m and installed the driver up to date.

i receive the following cuda runtime error (30) : unknown error code. 

any suggestion?

> ubuntu:~/FastPhoto$ python demo.py
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1512378422383/work/torch/lib/THC/THCGeneral.c line=70 error=30 : unknown error
Traceback (most recent call last):
  File "demo.py", line 34, in <module>
    p_wct.cuda(0)
  File "/home/deeperubuntu/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/deeperubuntu/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/deeperubuntu/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/deeperubuntu/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 152, in _apply
    param.data = fn(param.data)
  File "/home/deeperubuntu/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 216, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/deeperubuntu/anaconda2/lib/python2.7/site-packages/torch/_utils.py", line 61, in _cuda
    with torch.cuda.device(device):
  File "/home/deeperubuntu/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 186, in __enter__
    _lazy_init()
  File "/home/deeperubuntu/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 121, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /opt/conda/conda-bld/pytorch_1512378422383/work/torch/lib/THC/THCGeneral.c:70

**Comment by wesleyw72** [comment]
Could you try running with the flag '--cuda 0'. For example:
python demo.py --cuda 0

**Comment by ilyaskuzu** [comment]
it worked thank you
