### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by Sunsmiles2** [NVIDIA/FastPhotoStyle#69]
Hi,
I am running FastPhotoStyle code on Windows 10 and using Python 3.7, CUDA 10.0 and cuda 9.1. Although I made the change that was suggested to upgrade the version of Python from string to Byte, I am still getting the same error. Can you please suggest a fix for this issue.
 
Resize image: (803,538)->(803,538)
Resize image: (960,540)->(960,540)
Elapsed time in stylization: 2.325060
Elapsed time in propagation: 83.987388
Elapsed time in post processing: 0.015629
Traceback (most recent call last):
  File "demo.py", line 47, in <module>
    no_post=args.no_post
  File "D:\TrainImages\FastPhotoStyle-master\process_stylization.py", line 135, in stylization
    out_img = smooth_filter(out_img, cont_pilimg, f_radius=15, f_edge=1e-1)
  File "D:\TrainImages\FastPhotoStyle-master\smooth_filter.py", line 402, in smooth_filter
    best_ = smooth_local_affine(output_, input_, 1e-7, 3, H, W, f_radius, f_edge)
  File "D:\TrainImages\FastPhotoStyle-master\smooth_filter.py", line 333, in smooth_local_affine
    program = Program(src.encode('utf-8'), 'best_local_affine_kernel.cu'.encode('utf-8'))
  File "C:\Users\SD\Anaconda3\lib\site-packages\pynvrtc\compiler.py", line 49, in __init__
    self._interface = NVRTCInterface(lib_name)
  File "C:\Users\SD\Anaconda3\lib\site-packages\pynvrtc\interface.py", line 87, in __init__
    self._load_nvrtc_lib(lib_path)
  File "C:\Users\SD\Anaconda3\lib\site-packages\pynvrtc\interface.py", line 109, in _load_nvrtc_lib
    self._lib = cdll.LoadLibrary(name)
  File "C:\Users\SD\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\SD\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by tunip3** [comment]
how did you fix this?
Did you just run in it in linux?

**Comment by StrongerzZ** [comment]
@tunip3 @Sunsmiles2 
I have the same issue, have you solved it?
Please help me if solved！Thanks a lot!

**Comment by Louis24** [comment]
i got the same issue    program = Program(src.encode('utf-8'), 'best_local_affine_kernel.cu'.encode('utf-8'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pynvrtc\compiler.py", line 49, in __init__
    self._interface = NVRTCInterface(lib_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pynvrtc\interface.py", line 87, in __init__
    self._load_nvrtc_lib(lib_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pynvrtc\interface.py", line 109, in _load_nvrtc_lib
    self._lib = cdll.LoadLibrary(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
